### ISSUE TITLE
SQL file not found

### ISSUE THREAD

**Issue by sojijr** [ParamvirSingh55/Court-Case-Management-System.#1]
I have noticed that the .sql file is missing from the repository.

This missing SQL file is essential for setting up the database. Its absence hinders the use of the project that relies on the SQL file.

**Comment by ParamvirSingh55** [comment]
Thankyou for Feedback. I resolved that issue .Now You can get the SQL file with code in repository. Sent from Mail for Windows From: Damilola Soji-OderindeSent: 28 July 2023 02:53To: ParamvirSingh55/Court-Case-Management-System.Cc: SubscribedSubject: [ParamvirSingh55/Court-Case-Management-System.] SQL file not found (Issue #1) I have noticed that the .sql file is missing from the repository.This missing SQL file is essential for setting up the database. Its absence hinders the use of the project that relies on the SQL file.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by ParamvirSingh55** [comment]
I resolved that issue .Now You can get the SQL file with code in repository.
